services:
  frontend:
    image: 'ghcr.io/cleanwalk-org-asso/cleanwalk-org-v2/frontend:latest'
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.cleanwalk-front.rule=Host(`cleanwalk.online`)"
      - "traefik.http.routers.cleanwalk-front.entrypoints=websecure"
      - "traefik.http.routers.cleanwalk-front.tls.certresolver=letsencrypt"
      - "traefik.http.services.cleanwalk-front.loadbalancer.server.port=80"
      - "traefik.http.services.cleanwalk-front.loadbalancer.server.scheme=http"

    networks:
      - proxy
      - internal
    restart: always

  api:
    image: ghcr.io/cleanwalk-org-asso/cleanwalk-org-v2/api:latest
    env_file:
      - ./api/.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.cleanwalk-api.rule=Host(`api.cleanwalk.online`)"
      - "traefik.http.routers.cleanwalk-api.entrypoints=websecure"
      - "traefik.http.routers.cleanwalk-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.cleanwalk-api.loadbalancer.server.port=3000"
      - "traefik.http.services.cleanwalk-api.loadbalancer.server.scheme=http"

    networks:
      - proxy
      - internal
    restart: always

volumes:
  mongo_data:

networks:
  proxy:
    external: true
  internal:
    driver: bridge